// Generated by Selenium IDE
package com.example.integration;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class AttivazioneTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC1AllValid() {
    driver.get("http://localhost:8080/UniClass/PersonaleTA/AttivaUtenti.jsp");
    driver.findElement(By.id("matricola")).click();
    driver.findElement(By.id("matricola")).sendKeys("0512118330");
    driver.findElement(By.cssSelector("p > p:nth-child(2)")).click();
    driver.findElement(By.cssSelector("form:nth-child(5)")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("s.davanzo5@studenti.unisa.it");
    driver.findElement(By.cssSelector(".submit-btn")).click();
  }
  @Test
  public void tC2associazioneErrata() {
    driver.get("http://localhost:8080/UniClass/PersonaleTA/AttivaUtenti.jsp");
    driver.findElement(By.id("matricola")).click();
    driver.findElement(By.id("matricola")).sendKeys("0512118330");
    driver.findElement(By.cssSelector("p > p:nth-child(2)")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("s.davanzo5@studenti.unisa.it");
    driver.findElement(By.id("tipo")).click();
    {
      WebElement dropdown = driver.findElement(By.id("tipo"));
      dropdown.findElement(By.xpath("//option[. = 'Docente']")).click();
    }
    driver.findElement(By.cssSelector(".submit-btn")).click();
  }
  @Test
  public void tC3mailNotPresentDB() {
    driver.get("http://localhost:8080/UniClass/PersonaleTA/AttivaUtenti.jsp");
    driver.manage().window().setSize(new Dimension(1405, 1017));
    driver.findElement(By.id("matricola")).click();
    driver.findElement(By.id("matricola")).sendKeys("0512118330");
    driver.findElement(By.cssSelector("p > p:nth-child(2)")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("s.davanzo@studenti.unisa.it");
    {
      WebElement element = driver.findElement(By.cssSelector(".center-block"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".center-block"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".center-block"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".center-block")).click();
    driver.findElement(By.cssSelector(".submit-btn")).click();
  }
  @Test
  public void tC4emailNotFormatted() {
    driver.get("http://localhost:8080/UniClass/PersonaleTA/AttivaUtenti.jsp");
    driver.manage().window().setSize(new Dimension(1405, 1017));
    driver.findElement(By.id("email")).sendKeys("s.davanzostudenti@uni");
    driver.findElement(By.id("matricola")).click();
    driver.findElement(By.cssSelector("p > p:nth-child(1)")).click();
    driver.findElement(By.id("matricola")).click();
    driver.findElement(By.id("matricola")).sendKeys("0512118330");
    driver.findElement(By.id("tipo")).click();
    driver.findElement(By.id("tipo")).click();
    driver.findElement(By.cssSelector(".submit-btn")).click();
  }
  @Test
  public void tC5notPresentBothInfo() {
    driver.get("http://localhost:8080/UniClass/PersonaleTA/AttivaUtenti.jsp");
    driver.manage().window().setSize(new Dimension(1405, 1017));
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("s.davanzo@studenti.unisa.it");
    driver.findElement(By.id("matricola")).click();
    driver.findElement(By.id("matricola")).sendKeys("0512117895");
    driver.findElement(By.cssSelector(".submit-btn")).click();
  }
  @Test
  public void tC6notPresentBothAndNotFormattedEmail() {
    driver.get("http://localhost:8080/UniClass/PersonaleTA/AttivaUtenti.jsp");
    driver.manage().window().setSize(new Dimension(1405, 1017));
    driver.findElement(By.id("matricola")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("s.davanzostudenti@uni");
    driver.findElement(By.id("matricola")).click();
    driver.findElement(By.id("matricola")).sendKeys("0512117895");
    driver.findElement(By.cssSelector(".submit-btn")).click();
  }
  @Test
  public void tC7notPresentBothNotFormattedMatricola() {
    driver.get("http://localhost:8080/UniClass/PersonaleTA/AttivaUtenti.jsp");
    driver.manage().window().setSize(new Dimension(1405, 1017));
    driver.findElement(By.id("matricola")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("s.davanzo@studenti.unisa.it");
    driver.findElement(By.cssSelector("form:nth-child(5)")).click();
    driver.findElement(By.id("matricola")).click();
    driver.findElement(By.id("matricola")).sendKeys("aaaaa?");
    driver.findElement(By.cssSelector(".submit-btn")).click();
  }
  @Test
  public void tC8nothingGood() {
    driver.get("http://localhost:8080/UniClass/PersonaleTA/AttivaUtenti.jsp");
    driver.manage().window().setSize(new Dimension(1405, 1017));
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("s.davanzostudenti@uni");
    driver.findElement(By.id("matricola")).click();
    driver.findElement(By.id("matricola")).sendKeys("aaaaa");
    driver.findElement(By.cssSelector(".submit-btn")).click();
  }
}
